### ISSUE TITLE
hda file - lfs link ?

### ISSUE THREAD

**Issue by GlennPegden2** [rtts/win311#1]
I'm not really familiar with lfs, but should the hda be like that (a text file with what I assume is the hash of a file stored "somewhere") ?

**Comment by milesbuckton** [comment]
I get the error when trying to pull the Git LFS file `hda.img`:

> Error downloading object: hda.img (23f9edd): Smudge error: Error downloading hda.img (23f9edd8e5b58c28505885f0de689542b94c2d3fd3a3cf36d636af67d0f1b7bf): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by JaapJoris** [comment]
> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Yes, this is exactly what happened. Good error message :+1: 

I'll update the README with download link. Stay tuned.
